const FETCH_DATA_STATUS='FETCH/DATA/STATUS'
const FETCH_DATA_SUCCESS='FETCH/DATA/SUCCESS'
const FETCH_LOAD_DATA_SUCCESS='FETCH/LOAD/MORE/DATA'

export {
    FETCH_DATA_STATUS,FETCH_DATA_SUCCESS,FETCH_LOAD_DATA_SUCCESS
}
